name: torchmatch
channels:
- conda-forge
- pytorch
dependencies:
- python=3.8
- pytorch=1.7.0
- torchvision=0.8.0
- torchaudio=0.7.0
- cudatoolkit=10.1
- tensorboard=2.3.0
- pillow
- tqdm
- scikit-image
- scikit-learn
- imageio
- efficientnet-pytorch
- pandas
- seaborn
- albumentations
- scipy
- numpy=1.23.4
- imgaug
